version: 0.1


phases:
    build:
      commands:
        - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Richard Nevarez 2017.pdf
    - styles/main.css
    - images/*
